#!/usr/bin/python3

import requests
from bs4 import BeautifulSoup
import re
    #specifies URL
url = ('https://www.project1999.com/')
result = requests.get(url)
html = result.text
    #sets regex pattern to search the soup results
pattern = re.compile(r'[0-9][0-9][0-9]+')
    #Parsing the HTML
soup = BeautifulSoup( html, 'html.parser')
    #Searching through parsed data for specific html element
html_element = soup.find( 'td' , {'align' : 'right'})
    #applying the regex pattern
players = pattern.findall(html_element.text)
    #printing the output
print('Project 1999 players online: '+ players[0])
